### ISSUE TITLE
Bluez-util no longer used... pinaple is broken

### ISSUE THREAD

**Issue by Zakattacks** [Douglas6/pinaple#3]
Apparently, bluez got rid of bluez-utils and replaced it with bluetoothcli. I don't know the difference because this is all new to me, but here is the source: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=133961
The bluetoothcli seems to be part of the bluez package from apt.
I will look and see if there is anything I can change in the script but I have very little programming experience.
Anyway, well here is what happens when I try to run it:

```
pi@raspberry:~ $ sudo pinaple-agent --pin 1234
Traceback (most recent call last):
  File "/usr/local/bin/pinaple-agent", line 66, in <module>
    adapter_path = manager.DefaultAdapter()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "DefaultAdapter" with signature "" on interface "org.bluez.Manager" doesn't exist

```

**Comment by ghost** [comment]
I'm having the same issue.

**Comment by PHuhn** [comment]
After, I got dbus and gobject imports to work, now I am getting the following error:
```
pi@raspberrypi:~/pinaple $ sudo pinaple-agent --pin 1234
Traceback (most recent call last):
  File "/usr/local/bin/pinaple-agent", line 66, in <module>
    adapter_path = manager.DefaultAdapter()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "DefaultAdapter" with signature "" on interface "org.bluez.Manager" doesn't exist

```
I am assuming the changes in bluez is too much.
