### ISSUE TITLE
ImportError: No module named gobject

### ISSUE THREAD

**Issue by i621148** [Douglas6/pinaple#4]
I have the error:
pi@raspberrypi-Pyfi7poq4a:~ $ sudo pinaple-agent --pin 1234
Traceback (most recent call last):
  File "/usr/local/bin/pinaple-agent", line 15, in <module>
    import gobject
ImportError: No module named gobject

I think maybe you could modify pinaple-agent per:
https://stackoverflow.com/questions/37323567/install-gobject-module

Example:
#!/usr/bin/env python

# Author: Douglas Otwell
# This software is released to the public domain

# The Software is provided "as is" without warranty of any kind, either express or implied,
# including without limitation any implied warranties of condition, uninterrupted use,
# merchantability, fitness for a particular purpose, or non-infringement.

from gi.repository import GObject as gobject
import os
import sys
import dbus
import dbus.service
import dbus.mainloop.glib
import gobject
from optparse import OptionParser

**Comment by i621148** [comment]
That did get me past the error but now I am hitting the bluez error others have reported:

pi@raspberrypi-Pyfi7poq4a:~ $ sudo pinaple-agent --pin 1234
Traceback (most recent call last):
  File "/usr/local/bin/pinaple-agent", line 67, in <module>
    adapter_path = manager.DefaultAdapter()
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "DefaultAdapter" with signature "" on interface "org.bluez.Manager" doesn't exist

**Comment by i621148** [comment]
If someone is reading this so they can set up a bluetooth (PAN) personal area network with raspberry pi, I was able to get the procedure detailed here to work:
https://raspberrypi.stackexchange.com/questions/29504/how-can-i-set-up-a-bluetooth-pan-connection-with-a-raspberry-pi-and-an-ipod
